version: '3'

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - "es01:/usr/share/elasticsearch/data"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: changeme
      node.name: es01
      cluster.name: mycluster
      discovery.seed_hosts: es01
      cluster.initial_master_nodes: es01
      network.host: 0.0.0.0
      xpack.license.self_generated.type: basic
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "true"
      cluster.routing.allocation.disk.watermark.low: 93%
      cluster.routing.allocation.disk.watermark.high: 95%
    networks:
      - slo_percentile_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - "5601:5601"
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: changeme
    networks:
      - slo_percentile_network

volumes:
  es01:
    driver: local

networks:
  slo_percentile_network:
    external: true
